---
install:
- yes | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get update -qq
- sudo apt-get install latex-xcolor texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra
- wget https://raw.github.com/graingert/Dropbox-Uploader/patch-1/dropbox_uploader.sh
  -O dropbox_uploader.sh
script:
- make
after_success:
- if [ "$DROPBOX_UPLOADER" ]; then bash dropbox_uploader.sh upload cv.pdf; fi
env:
  global:
  - secure: ! 'Kqj5Zt16qD5UmdMrnfNtd1X1s9+qGG5/v8SUazyQIgwxPcARCbWsKPKwJ2EF

      c5k/MdZoPZYm4r8dBZVEZ2+WlCXy32jYKMutGPCnMvPj7YuyMTOCcpFMMNSb

      qcfso3w4io4iTWLfGBnD/5ePEp7u5jMVCSyRGf9e0BajOhc+29c='
  - secure: ! 'WjwcTP7IqkuK8FEZi28I1G6PrGLLMSRG/9E1W6oMLtO73S09XFYqAArcKM+n

      Gb9KZT8L+K2EE7zZNKgYH9UGJDe9QcHYqAto2vdMC7kwEUBxgqRzsHqrnxGm

      6vESsIAypqQ1jg5T9j1CaKVOGzGVD+AN23Up996CTeGgmqTSrKc='
  - secure: ! 'OmRvloPeQ56f+ZAG8XTax4L7qQwW26tt4DlN3mYFsCpl7MLtnvuSDJG6s2NF

      m1kKi+Emt7uE35NwTJdAQC4Gvjfv3WnmbhKBldaP9M/hU8bI/w0n7xCvtDvr

      JAUk5mkKKHtJKDoA8pOb2oov8tcHPt06T2fq0gC10yBhktgIQZk='
  - secure: ! 'lFa6+qVZFPRp+JfSowqwEdqvOHebHKiH1DyjdnXQhhcfvOKwpPugYgr4ycMR

      IE2pUTfNDfvo/M9CpZ3/PGCrmdYYsfS9vSw9zmY0ZC5pM4A6yZQ4bWZk6mMJ

      7naBgOM1zfYz0dhDV/9g1yit5TY8oVYWW6HCfoYEg+34ZznXdPQ='
  - secure: ! 'CosGWDVQR8e9APooS2SOihG559GonGjrnjM4cbIGNEQqh1NdjlkqaNOF6XKZ

      rUSdWYSL0oknaKSY4b2wwyTFoQq5fvaBSVWKn0ISs34KhVkxWB0ZvBZvk7v4

      XUPE1/hMGYjCSeWA7mQuUmSjWfu/+oi1ZHt+CiJQ5sHfRQ90n/w='
  - secure: ! 'V5ALh65yICrS8u+keGA89TLouoxTqK9Pu0/+E1S4A4g64AFFwGQKFEV4uSrt

      IHRaOTkJ4Po0CxH2BSPgYeuqBdJN8KdkAJYi/9BkW7QQoDoiJk1NuikbpfAA

      f8UjLZy3A77anIFL0OFAGZuB7eLqgfZK8fqoISkcoq3+hr28H8I='
